### ISSUE TITLE
`with-database`

### ISSUE THREAD

**Issue by siiky** [ursetto/sql-de-lite#14]
Howdy!

Would you be willing to include a new macro, a simple wrapper for `call-with-database`? I'm using this:

```scm
(define-syntax with-database
  (syntax-rules ()
    ((with-database filename db expr ...)
     (call-with-database filename (lambda (db) expr ...)))))
```

It's supposed to be used like this:

```scm
(with-database 'memory db
  (query fetch-all (sql db "..."))
  ...)
```

**Comment by ursetto** [comment]
It seems more Common Lispish than Scheme-y to me to tell you the truth. `with-*` calls usually are procedures taking a zero-arg thunk rather than macros in Scheme. For example with-database would typically set a hypothetical (current-database) behind the scenes, which you could then use in your thunk. 

I think it’s perfectly reasonable to define in your own code though. I might rename it to emphasize it doesn’t take a thunk (I don’t have a good alternative name here) but that’s author’s choice. In general I have shied away from providing macro shortcuts in APIs unless really needed, and in this case, I don’t necessarily want to add one that just removes a set of parens (again, kind of CL-like).

If you have examples of other good scheme APIs that do this I’ll reconsider.

**Comment by siiky** [comment]
Sounds reasonable to me! It was just a suggestion and it's easy to define anyway. :)

RE examples I can't think of any right now.
